### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tomjakubowski** [msqrt/shader-printf#1]
This project is awesome, but I'm unsure if I'm allowed to use its code or not in my own projects because there's no [apparent license](https://github.com/msqrt/shader-printf/search?utf8=%E2%9C%93&q=copyright+OR+license&type=) on it.

If you'd like others to use this library, could you [clarify its license](https://choosealicense.com/no-license/)? A LICENSE or COPYING file in the repository and/or a copyright + license inline in the shaderprintf.h header would do :-)

**Comment by msqrt** [comment]
Thanks, this is a very good point -- I've never really released code so this slipped off my mind. Much of this is still work in progress but I added license disclaimers so you can start using it without any uncertainties. It's under the MIT license.
