### ISSUE TITLE
unwanted line offset

### ISSUE THREAD

**Issue by tsoj** [msqrt/shader-printf#2]
https://github.com/msqrt/shader-printf/blob/e74046eccd7dfb7a2cdb870cc712d3cdfe3854ab/shader-printf/shaderprintf.h#L212
I think here the `bufferInsertOffset` should be after the `'\n'`. Then compiler errors work in my environment.

**Comment by msqrt** [comment]
You're exactly right, good point! I think I tested this mostly by pasting erroneous words after lines, and my shader compiler seems to give the error for that on the following line. Pushed a fix that simply increments the offset before checking to break.
