### ISSUE TITLE
`max()` function not declared

### ISSUE THREAD

**Issue by tsoj** [msqrt/shader-printf#3]
https://github.com/msqrt/shader-printf/blob/e74046eccd7dfb7a2cdb870cc712d3cdfe3854ab/shader-printf/shaderprintf.h#L201
On my Linux machine I get this error:
```
shader-printf/shader-printf/shaderprintf.h:219:48: error: ‘max’ was not declared in this scope
  219 |  if (extension != std::string::npos) version = max(extension, version);
```
A simple fix would be to use `std::max()` instead.

**Comment by msqrt** [comment]
Ah, right. The MSVC headers that are already included don't contain std::max, so I went for a ternary operator instead.
