### ISSUE TITLE
-Wshadow gcc warning

### ISSUE THREAD

**Issue by tsoj** [msqrt/shader-printf#4]
https://github.com/msqrt/shader-printf/blob/e74046eccd7dfb7a2cdb870cc712d3cdfe3854ab/shader-printf/shaderprintf.h#L225
this variable shadows this declaration:
https://github.com/msqrt/shader-printf/blob/e74046eccd7dfb7a2cdb870cc712d3cdfe3854ab/shader-printf/shaderprintf.h#L185

And thus issues a warning when the gcc compiler option `-Wshadow` is enabled:

```
shader-printf/shader-printf/shaderprintf.h:246:8: warning: declaration of ‘inString’ shadows a previous local [-Wshadow]
```
A simple fix would be to insert curly braces `{}` around line 183 to 196.

**Comment by msqrt** [comment]
Fixed by doing what you suggested.
