### ISSUE TITLE
glGetProgramResourceiv bufSize should not be in bytes.

### ISSUE THREAD

**Issue by realazthat** [msqrt/shader-printf#5]
On line 52: https://github.com/msqrt/shader-printf/blob/e7b25ffb6e5557b48a1010c0a829e51d56903ad6/shader-printf/shaderprintf.h#L52

```C++
	glGetProgramResourceiv(program, GL_SHADER_STORAGE_BLOCK, glGetProgramResourceIndex(program, GL_SHADER_STORAGE_BLOCK, "printfBuffer"), 1, &prop, sizeof(binding), nullptr, &binding);

```

`sizeof(binding)` is wrong, it should just be `1`.

See https://www.khronos.org/opengl/wiki/Example_Code#Program_introspection for proper example usage. See https://github.com/KhronosGroup/OpenGL-API/issues/52 about this confusing naming.

**Comment by msqrt** [comment]
You're absolutely right, thanks for pointing this out! It's fixed now -- sorry about the delay.
